baseURL = "/"
relativeurls = true
languageCode = "en-us"
title = "Mara Averick"
theme = "kube"
description = "Tweeting is like 95 percent of what I do..."
# Enable emoji
enableEmoji = true
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Mara Averick" # add your company name
  github = "batpigandme" # add your github profile name
  twitter = "dataandme" # add your twitter profile
  email = "maraaverick@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
